version: "3.8"
services:
  backend:
    build: ./
    container_name: traffic-backend
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - redis
    environment:
      - NODE_ENV=production # ✅ Run in production mode
      - DATABASE_URL=mysql://root:password@mysql:3306/traffic-app
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - app-network

  mysql:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: traffic-app
    ports:
      - "3307:3306"
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:


volumes:
  mysql_data:
